@baseUrl = http://localhost:5000/api

###
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Dũng Nguyễn",
    "email": "dungnguyenq1w2@gmail.com",
    "password": "123456" ,
    "confirmPassword": "123456" 
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "dungnguyenq1w2@gmail.com",
    "password": "123456" 
}

###
# @name getNewToken
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6IiIsImVtYWlsIjoibGVuZ29jZHUxMjM2NTR0bEBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NjkwODM2NDUsImV4cCI6MTY3MTY3NTY0NX0.YakxTNbxgjQfThlpUkgxmCnWKr4sbyH5al1NJsDFHbo"
}

###
# @name logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6Ik5ndXnhu4VuIFThuqVuIETFqW5nIiwiaWF0IjoxNjY3MjMwOTgzLCJleHAiOjE2NjcyMzA5ODh9.JscG57JevEBOpFkKn7MqepsuTTakMMWQZY2tBo91vfM"
}

