@baseUrl = http://localhost:5000/api

###
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Nguyễn Tấn Dũng",
    "email": "hoduy220@gmail.com",
    "password": "123456" ,
    "confirmPassword": "123456" 
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "dungnguyenq1w2@gmail.com",
    "password": "123456" 
}

###
# @name getNewToken
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwibmFtZSI6IkTFqW5nIE5ndXnhu4VuIiwiaW1hZ2UiOm51bGwsImVtYWlsIjoiZHVuZ25ndXllbnExdzJAZ21haWwuY29tIiwiaXNfYXV0aCI6MSwiaWF0IjoxNjY4NzgyNjIyLCJleHAiOjE2NzEzNzQ2MjJ9.E6Q4z7t0q_my50BUSYSThCIdYNgkiVTgiTeibvSZYRc"
}

###
# @name logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6Ik5ndXnhu4VuIFThuqVuIETFqW5nIiwiaWF0IjoxNjY3MjMwOTgzLCJleHAiOjE2NjcyMzA5ODh9.JscG57JevEBOpFkKn7MqepsuTTakMMWQZY2tBo91vfM"
}

