@baseUrl = http://localhost:5000/api

###
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Dũng Nguyễn",
    "email": "dungnguyenq1w2@gmail.com",
    "password": "123456" ,
    "confirmPassword": "123456" 
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "dungnguyenq1w2@gmail.com",
    "password": "123456" 
}

###
# @name getNewToken
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkzDqiBOZ-G7jWMgRHUgMSIsImltYWdlIjoiIiwiZW1haWwiOiJkdTFAZ21haWwuY29tIiwiaXNfYXV0aCI6MSwiaWF0IjoxNjcyODQ3OTc4LCJleHAiOjE2NzU0Mzk5Nzh9.lg-79E-5z86RfM6VaTHHAwbLPpaIcwVkr7gCM2Fb0vk"
}

###
# @name logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6Ik5ndXnhu4VuIFThuqVuIETFqW5nIiwiaWF0IjoxNjY3MjMwOTgzLCJleHAiOjE2NjcyMzA5ODh9.JscG57JevEBOpFkKn7MqepsuTTakMMWQZY2tBo91vfM"
}

###
# @name sendMailIdentify
POST {{baseUrl}}/auth/identify
Content-Type: application/json

{
   "email": "hoduy220@gmail.com"
}

###
# @name resetPassword
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
   "newPassword": "123456",
   "confirmPassword": "123456",
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJob2R1eTIyMEBnbWFpbC5jb20iLCJpYXQiOjE2NzI2NTQwNDQsImV4cCI6MTY3MjY1NDE2NH0.nGwLUFwAvD9rb5yGokbPN0iRZQ2nqjxXCXQpILJMOac"
}
