@baseUrl = http://localhost:5000/api

###
# @name getGroup
GET {{baseUrl}}/groups/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6bnVsbCwiZW1haWwiOiJsZW5nb2NkdTEyMzY1NHRsQGdtYWlsLmNvbSIsImlzX2F1dGgiOjEsImlhdCI6MTY2ODkxMzc5MiwiZXhwIjoxNjY4OTE3MzkyfQ.Gr2TXnvkVvF-ksFsH9qVHNuDR596oAPLEKyszw8me0Y

###
# @name getAllGroups
GET {{baseUrl}}/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6IiIsImVtYWlsIjoibGVuZ29jZHUxMjM2NTR0bEBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NjkwODM2NDUsImV4cCI6MTY2OTA4NzI0NX0.3hsWYK5NZelZ-YmPnWEE-ZXjtb6k7rivAdN0JvVaPj4

###
# @name promoteParticipant
PUT {{baseUrl}}/groups/1/promote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6IiIsImVtYWlsIjoibGVuZ29jZHUxMjM2NTR0bEBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NjkwODM2NDUsImV4cCI6MTY2OTA4NzI0NX0.3hsWYK5NZelZ-YmPnWEE-ZXjtb6k7rivAdN0JvVaPj4
Content-Type: application/json

{
    "userId": 2
}

###
# @name demoteParticipant
PUT {{baseUrl}}/groups/1/demote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6IiIsImVtYWlsIjoibGVuZ29jZHUxMjM2NTR0bEBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NjkwODM2NDUsImV4cCI6MTY2OTA4NzI0NX0.3hsWYK5NZelZ-YmPnWEE-ZXjtb6k7rivAdN0JvVaPj4
Content-Type: application/json

{
    "userId": 2
}

###
# @name demoteParticipant
PUT {{baseUrl}}/groups/1/kick-out
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6IiIsImVtYWlsIjoibGVuZ29jZHUxMjM2NTR0bEBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NjkwODM2NDUsImV4cCI6MTY2OTA4NzI0NX0.3hsWYK5NZelZ-YmPnWEE-ZXjtb6k7rivAdN0JvVaPj4
Content-Type: application/json

{
    "userId": 2
}

###
# @name inviteParticipant
POST {{baseUrl}}/groups/2/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkzDqiBOZ-G7jWMgRHUiLCJpbWFnZSI6IiIsImVtYWlsIjoibGVuZ29jZHUxMjM2NTR0bEBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NjkwODc1ODAsImV4cCI6MTY2OTA5MTE4MH0.fQTB7CU0QHG6-KzgW1SU_sgiEkiz7unk_oG-CWuQoyI

