@baseUrl = http://localhost:5000/api

###
# @name getGroup
GET {{baseUrl}}/groups/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6Ik5ndXnhu4VuIFThuqVuIETFqW5nIiwiaW1hZ2UiOm51bGwsImVtYWlsIjoiaG9kdXkyMjBAZ21haWwuY29tIiwiaXNfYXV0aCI6MSwiaWF0IjoxNjY4Nzg3OTM5LCJleHAiOjE2Njg3ODg1Mzl9.b4RUK7znH5YSmlo3bogK9UG4F_1BsEpl6dK2tjMd8BU