@baseUrl = http://localhost:5000/api

###
# @name getAllNotifications
GET {{baseUrl}}/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWUiOiJOZ3V54buFbiBU4bqlbiBExaluZyIsImltYWdlIjoiIiwiZW1haWwiOiJkdW5nbmd1eWVucTF3MkBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NzE4MTA1MzEsImV4cCI6MTY3MTgxNDEzMX0.Zzu6DZxuKPXGGZZpZCrZunXAmuWxpwsuv94WKteSBDA

###
# @name addPresentation
POST {{baseUrl}}/notifications
Content-Type: application/json

{
    "user_id": "27",
    "content": "content test 2",
    "link": "link test 2"
}
