@baseUrl = http://localhost:5000/api

###
# @name getPresentationOfOneUser
GET {{baseUrl}}/presentations/3

###
# @name deletePresentationById
DELETE {{baseUrl}}/presentations/5

###
# @name getAllSlides
GET {{baseUrl}}/presentations/1/slides

###
# @name checkCode
POST {{baseUrl}}/presentations/checkCode
Content-Type: application/json

{
    "code": "01234567"
}

###
# @name addPresentation
POST {{baseUrl}}/presentations/add
Content-Type: application/json

{
    "hostId": 3, 
    "name": "abc"
}

###
# @name getPresentationById
GET {{baseUrl}}/presentations/presentationId/1

###
# @name updatePresentationName
PUT {{baseUrl}}/presentations/updateName
Content-Type: application/json

{
    "presentationId": 5, 
    "name": "abc"
}
