@baseUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWUiOiJOZ3V54buFbiBU4bqlbiBExaluZyIsImltYWdlIjoiIiwiZW1haWwiOiJkdW5nbmd1eWVucTF3MkBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NzIwNDUxNTgsImV4cCI6MTY3MjY0OTk1OH0.AurgbR4agLvq4Qnz2RKNJGFZgPT6TaVty_URmTvD9t4

###
# @name test
GET {{baseUrl}}/presentations/test

###
# @name getPresentationOfOneUser
GET {{baseUrl}}/presentations
#Authorization: Bearer {{token}}

###
# @name getPresentationOfGroup
GET {{baseUrl}}/presentations/group/2
Authorization: Bearer {{token}}

###
# @name getPresentationForHostById
GET {{baseUrl}}/presentations/5/host?presentationGroupId=4
Authorization: Bearer {{token}}

###
# @name getPresentationForMemberById
GET {{baseUrl}}/presentations/5/member?presentationGroupId=4
# Authorization: Bearer {{token}}

###
# @name deletePresentationById
DELETE {{baseUrl}}/presentations/5
Authorization: Bearer {{token}}

###
# @name checkCode
POST {{baseUrl}}/presentations/checkCode
Content-Type: application/json

{
    "code": "01234567"
}

###
# @name addPresentation
POST {{baseUrl}}/presentations/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "hostId": 3, 
    "name": "abc"
}

###
# @name getPresentationById
GET {{baseUrl}}/presentations/1
Authorization: Bearer {{token}}

###
# @name updatePresentationName
PUT {{baseUrl}}/presentations/updateName
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "presentationId": 5, 
    "name": "abc"
}

###
# @name createPresentationCode
POST {{baseUrl}}/presentations/createCode/3
Authorization: Bearer {{token}}

###
# @name getActivePresentationsOfGroup
GET {{baseUrl}}/presentations/group/1/active
# Authorization: Bearer {{token}}