@baseUrl = http://localhost:5000/api

###
# @name getAllQuestions
GET {{baseUrl}}/questions?presentationId=5&presentationGroupId=1

###
# @name addQuestion
POST {{baseUrl}}/questions
Content-Type: application/json

{
    "content":"test test",
    "presentation_id": 5,
    "presentation_group_id": 4
}

###
# @name addVote
POST {{baseUrl}}/questions/1/vote