@baseUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWUiOiJOZ3V54buFbiBU4bqlbiBExaluZyIsImltYWdlIjoiIiwiZW1haWwiOiJkdW5nbmd1eWVucTF3MkBnbWFpbC5jb20iLCJpc19hdXRoIjoxLCJpYXQiOjE2NzIwNDUxNTgsImV4cCI6MTY3MjY0OTk1OH0.AurgbR4agLvq4Qnz2RKNJGFZgPT6TaVty_URmTvD9t4

###
# @name getAllSlides
POST {{baseUrl}}/slides
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "presentationId": 1
}

###
# @name getFirstSlideOfPresentation
POST {{baseUrl}}/slides/first-slide
Content-Type: application/json

{
    "presentationId": 1
}

###
# @name getSlideById
GET {{baseUrl}}/slides/1

###
# @name getSlideResultForHost
GET {{baseUrl}}/slides/1/host
Authorization: Bearer {{token}}

###
# @name getSlideResultForMember
GET {{baseUrl}}/slides/1/member?memberId=3
