@baseUrl = http://localhost:5000/api

###
# @name getAllSlides
POST {{baseUrl}}/slides
Content-Type: application/json

{
    "presentationId": 1
}

###
# @name getSlideById
GET {{baseUrl}}/slides/1

###
# @name getSlideResultForHost
GET {{baseUrl}}/slides/1/host

###
# @name getSlideResultForGuest
GET {{baseUrl}}/slides/1/guest?guestId=1
# Content-Type: application/json

# {
#     "guestId": "1"
# }